### ISSUE TITLE
In v1.x, relative css `url(../<path>)` functions are transformed to broccoli funnel paths

### ISSUE THREAD

**Issue by void-mAlex** [ember-cli/ember-cli-clean-css#196]
this issue is currently blocking https://github.com/ember-cli/ember-cli/issues/8457 from moving forward and is part of the investigation done to bring this addon into the default blueprints for ember apps and addons

_all examples are from SuperRentals repo [https://github.com/ember-learn/super-rentals](url) with this addon added manually to the project_

```css
.tomster {
  background: url(../assets/images/teaching-tomster-756a14cc8225582bf530b5d0c624db4d.png) no-repeat;
  background-size: contain;
  height: 200px;
  width: 200px;
  top: -25px
}
```
becomes
```css
.tomster {
  background: url(../../../../tmp/broccoli-1189SeGOWMQ9D4Gu/out-201-funnel/assets/images/teaching-tomster-756a14cc8225582bf530b5d0c624db4d.png);
  background-size: contain;
  background-repeat: no-repeat;
  height: 200px;
  width: 200px;
  position: relative;
  top: -25px
}
```
for absolute urls (at least on the builds on my machine it's behaving)

also to have parity with current minified css output duplicate css property declarations need to be removed as well
original css output
```css
.menu {
  height: 4em;
  background-color: #e46855
}
```
addon css output
```css
.menu {
  height: 4em;
  background-color: #677ae4;
  background-color: #05526a;
  background-color: #e46855
}
```
